# Generated by Django 6.0 on 2025-12-15 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_options_and_more'),
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance'),
        ),
    ]
