# Generated by Django 6.0 on 2025-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_alter_overtime_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='overtime',
            name='approval_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='overtime',
            name='decision_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
