# Generated by Django 6.0 on 2025-12-16 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_created_at_and_more'),
        ('overtime', '0003_remove_overtime_approved_remove_overtime_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='approval_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('H', 'On Hold')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='attendance.attendance'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='decision_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='overtime_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
