# Generated by Django 6.0 on 2025-12-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_check_in_time_attendance_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
