# Generated by Django 6.0 on 2025-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_is_late'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_late',
        ),
        migrations.AddField(
            model_name='attendance',
            name='on_time',
            field=models.BooleanField(default=True),
        ),
    ]
