# Generated by Django 6.0 on 2025-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_is_late_attendance_on_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='on_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='punctuality_status',
            field=models.BooleanField(blank=True, help_text='True = On time, False = Late, None = Not applicable', null=True),
        ),
    ]
