# Generated by Django 6.0 on 2025-12-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_on_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punctuality_status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='on_time_checkin',
            field=models.BooleanField(default=False, help_text='True if employee checked in on time, else False'),
        ),
    ]
